name: Täglicher Auto-Push

on:
  schedule:
    - cron: '0 8 * * *' # Täglich um 8:00 Uhr UTC (9:00 Uhr in Deutschland)
  workflow_dispatch: # Optional manueller Start

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install pytrends

      - name: Skript ausführen
        run: python artikel_automat.py

      - name: Änderungen committen
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "🔄 Auto-Update via ArtikelAutomat" || echo "Keine Änderungen"
          git push
